[package]
name = "rsonpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rsonpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
pyo3-file = "0.7.0"
rsonpath-lib = "0.8.2"
