[package]
name = "rsonpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rsonpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
rsonpath-lib = "0.9.4"
rsonpath-syntax = "0.4.0"
